package com.jkdr.abyssalascentdimensionpatcher.mixins.invokers; 

import net.minecraft.core.BlockPos;
import net.minecraft.world.level.LevelSimulatedReader;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.levelgen.feature.trunkplacers.TrunkPlacer; // <<< The Correct Target
import net.minecraft.world.level.levelgen.feature.configurations.TreeConfiguration;
import net.minecraft.util.RandomSource;

import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.gen.Invoker;

import java.util.function.BiConsumer;

// Correct the target class to TrunkPlacer
@Mixin(TrunkPlacer.class) // Target the class directly
public interface MixinTrunkPlacer {
    
    // The @Invoker must use the method's name
    @Invoker("setDirtAt")
    static void invokeSetDirtAt(LevelSimulatedReader level, BiConsumer<BlockPos, BlockState> setter, RandomSource random, BlockPos pos, TreeConfiguration config) {
        // Implementation is generated by Mixin
        throw new AssertionError("Mixin Invoker failed to inject!"); 
    }
}